apiVersion: v1
kind: Service
metadata:
  name: invenlore-user-service
  labels:
    k8s-app: invenlore-user-service
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: health
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    k8s-app: invenlore-user-service
