apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invenlore-user-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: invenlore-user-service=invenlore/invenlore-user-service
    argocd-image-updater.argoproj.io/invenlore-user-service.force-update: "true"
    argocd-image-updater.argoproj.io/invenlore-user-service.update-strategy: semver
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: invenlore-services
  sources:
    - repoURL: https://github.com/invenlore/user.service.git
      targetRevision: master
      path: .helm
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
