apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invenlore-user-service
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: invenlore-services
  sources:
  - repoURL: https://github.com/invenlore/user.service.git
    targetRevision: master
    path: .argocd/manifests

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
