apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invenlore-user-service
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: invenlore-services
  sources:
    - repoURL: https://github.com/invenlore/user.service.delivery.git
      targetRevision: master
      path: .helm
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
